/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionDeMovimientos.vista;

import gestionDeMovimientos.controlador.ControladorInsertardoDeDatos;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author jesus
 */
public class JDialogInsertadoDeDatos extends javax.swing.JDialog {

    private ControladorInsertardoDeDatos controladorInsertadoDeDatos;
    private boolean flagNumeroEmpleado = false;
    private boolean flagNombreEmpleado = false;
    private boolean flagApellidoEmpleado = false;
    private boolean flagIdMovimiento = false;
    private boolean flagImporteMovimiento = false;
    private boolean flagFechaMovimiento = false;
    private boolean flagDescripcionMovimiento = false;

    /**
     * Creates new form JFrameInsertadoDeDatos
     */
    public JDialogInsertadoDeDatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controladorInsertadoDeDatos = new ControladorInsertardoDeDatos(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInsertarDatos = new javax.swing.JPanel();
        jLabelInsertarDatos = new javax.swing.JLabel();
        jTextFieldNumerodeEmpleado = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldNumeroDeMovimiento = new javax.swing.JTextField();
        jTextFieldImporte = new javax.swing.JTextField();
        jComboBoxTipo = new javax.swing.JComboBox();
        jTextFieldFecha = new javax.swing.JTextField();
        jButtonInsertarTexto = new javax.swing.JButton();
        jButtonInsertarBinario = new javax.swing.JButton();
        jButtonInsertarObjeto = new javax.swing.JButton();
        jButtonInsertarXML = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelInsertarDatos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelInsertarDatos.setText("Insertar Datos");

        jTextFieldNumerodeEmpleado.setForeground(new java.awt.Color(126, 126, 126));
        jTextFieldNumerodeEmpleado.setText("Numero");
        jTextFieldNumerodeEmpleado.setToolTipText("Numero de Empleado");
        jTextFieldNumerodeEmpleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNumerodeEmpleadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumerodeEmpleadoFocusLost(evt);
            }
        });
        jTextFieldNumerodeEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumerodeEmpleadoKeyTyped(evt);
            }
        });

        jTextFieldNombre.setForeground(new java.awt.Color(126, 126, 126));
        jTextFieldNombre.setText("Nombre");
        jTextFieldNombre.setToolTipText("Nombre del Empleado");
        jTextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusLost(evt);
            }
        });

        jTextFieldApellido.setForeground(new java.awt.Color(126, 126, 126));
        jTextFieldApellido.setText("Apellidos");
        jTextFieldApellido.setToolTipText("Apellidos del Empleado");
        jTextFieldApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldApellidoFocusLost(evt);
            }
        });

        jTextFieldNumeroDeMovimiento.setForeground(new java.awt.Color(126, 126, 126));
        jTextFieldNumeroDeMovimiento.setText("Numero de Movimiento");
        jTextFieldNumeroDeMovimiento.setToolTipText("Id de Movimiento");
        jTextFieldNumeroDeMovimiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNumeroDeMovimientoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumeroDeMovimientoFocusLost(evt);
            }
        });
        jTextFieldNumeroDeMovimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroDeMovimientoKeyTyped(evt);
            }
        });

        jTextFieldImporte.setForeground(new java.awt.Color(126, 126, 126));
        jTextFieldImporte.setText("Importe");
        jTextFieldImporte.setToolTipText("Importe de Movimiento");
        jTextFieldImporte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldImporteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldImporteFocusLost(evt);
            }
        });
        jTextFieldImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldImporteActionPerformed(evt);
            }
        });
        jTextFieldImporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldImporteKeyTyped(evt);
            }
        });

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gasto", "Ingreso" }));
        jComboBoxTipo.setToolTipText("Tipo de Movimiento");

        jTextFieldFecha.setForeground(new java.awt.Color(126, 126, 126));
        jTextFieldFecha.setText("20/01/2000");
        jTextFieldFecha.setToolTipText("Fecha De Movimiento");
        jTextFieldFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFechaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldFechaFocusLost(evt);
            }
        });

        jButtonInsertarTexto.setText("Texto");
        jButtonInsertarTexto.setToolTipText("Insertar los datos en el archivo Texto");
        jButtonInsertarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarTextoActionPerformed(evt);
            }
        });

        jButtonInsertarBinario.setText("Binario");
        jButtonInsertarBinario.setToolTipText("Insertar los datos en el archivo Binario");
        jButtonInsertarBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarBinarioActionPerformed(evt);
            }
        });

        jButtonInsertarObjeto.setText("Objeto");
        jButtonInsertarObjeto.setToolTipText("Insertar los datos en el archivo Objeto");
        jButtonInsertarObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarObjetoActionPerformed(evt);
            }
        });

        jButtonInsertarXML.setText("XML");
        jButtonInsertarXML.setToolTipText("Insertar los datos en el archivo XML");
        jButtonInsertarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarXMLActionPerformed(evt);
            }
        });

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setForeground(new java.awt.Color(126, 126, 126));
        jTextAreaDescripcion.setRows(5);
        jTextAreaDescripcion.setText("Descripción");
        jTextAreaDescripcion.setToolTipText("Descripción de movimiento");
        jTextAreaDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextAreaDescripcionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextAreaDescripcionFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        javax.swing.GroupLayout jPanelInsertarDatosLayout = new javax.swing.GroupLayout(jPanelInsertarDatos);
        jPanelInsertarDatos.setLayout(jPanelInsertarDatosLayout);
        jPanelInsertarDatosLayout.setHorizontalGroup(
            jPanelInsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertarDatosLayout.createSequentialGroup()
                .addGroup(jPanelInsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelInsertarDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanelInsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelInsertarDatosLayout.createSequentialGroup()
                            .addGap(242, 242, 242)
                            .addComponent(jLabelInsertarDatos))
                        .addGroup(jPanelInsertarDatosLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanelInsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelInsertarDatosLayout.createSequentialGroup()
                                    .addComponent(jButtonInsertarTexto)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonInsertarBinario)
                                    .addGap(26, 26, 26)
                                    .addComponent(jButtonInsertarObjeto)
                                    .addGap(31, 31, 31)
                                    .addComponent(jButtonInsertarXML))
                                .addGroup(jPanelInsertarDatosLayout.createSequentialGroup()
                                    .addComponent(jTextFieldNumerodeEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldNumeroDeMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(16, 16, 16)
                            .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanelInsertarDatosLayout.setVerticalGroup(
            jPanelInsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertarDatosLayout.createSequentialGroup()
                .addComponent(jLabelInsertarDatos)
                .addGap(33, 33, 33)
                .addGroup(jPanelInsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumerodeEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumeroDeMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelInsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertarBinario)
                    .addComponent(jButtonInsertarObjeto)
                    .addComponent(jButtonInsertarXML)
                    .addComponent(jButtonInsertarTexto)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInsertarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInsertarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNumerodeEmpleadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumerodeEmpleadoFocusGained
        flagNumeroEmpleado = controladorInsertadoDeDatos.VaciarCampos(jTextFieldNumerodeEmpleado, flagNumeroEmpleado);
    }//GEN-LAST:event_jTextFieldNumerodeEmpleadoFocusGained

    private void jTextFieldNumerodeEmpleadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumerodeEmpleadoFocusLost
        if (jTextFieldNumerodeEmpleado.getText().isEmpty()) {
            flagNumeroEmpleado = controladorInsertadoDeDatos.RellenarCampos("Numero", jTextFieldNumerodeEmpleado, flagNumeroEmpleado);

        }
    }//GEN-LAST:event_jTextFieldNumerodeEmpleadoFocusLost

    private void jTextFieldNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusGained
        flagNombreEmpleado = controladorInsertadoDeDatos.VaciarCampos(jTextFieldNombre, flagNombreEmpleado);
    }//GEN-LAST:event_jTextFieldNombreFocusGained

    private void jTextFieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusLost
        if (jTextFieldNombre.getText().isEmpty()) {
            flagNombreEmpleado = controladorInsertadoDeDatos.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);

        }
    }//GEN-LAST:event_jTextFieldNombreFocusLost

    private void jTextFieldApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldApellidoFocusGained
        flagApellidoEmpleado = controladorInsertadoDeDatos.VaciarCampos(jTextFieldApellido, flagApellidoEmpleado);
    }//GEN-LAST:event_jTextFieldApellidoFocusGained

    private void jTextFieldApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldApellidoFocusLost
        if (jTextFieldApellido.getText().isEmpty()) {
            flagApellidoEmpleado = controladorInsertadoDeDatos.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);

        }
    }//GEN-LAST:event_jTextFieldApellidoFocusLost

    private void jTextFieldNumeroDeMovimientoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumeroDeMovimientoFocusGained
        flagIdMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextFieldNumeroDeMovimiento, flagIdMovimiento);
    }//GEN-LAST:event_jTextFieldNumeroDeMovimientoFocusGained

    private void jTextFieldNumeroDeMovimientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumeroDeMovimientoFocusLost
        if (jTextFieldNumeroDeMovimiento.getText().isEmpty()) {
            flagIdMovimiento = controladorInsertadoDeDatos.RellenarCampos("Numero de Movimiento", jTextFieldNumeroDeMovimiento, flagIdMovimiento);

        }
    }//GEN-LAST:event_jTextFieldNumeroDeMovimientoFocusLost

    private void jTextFieldImporteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldImporteFocusGained
        flagImporteMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextFieldImporte, flagImporteMovimiento);
    }//GEN-LAST:event_jTextFieldImporteFocusGained

    private void jTextFieldImporteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldImporteFocusLost
        if (jTextFieldImporte.getText().isEmpty()) {
            flagImporteMovimiento = controladorInsertadoDeDatos.RellenarCampos("Importe", jTextFieldImporte, flagImporteMovimiento);

        }
    }//GEN-LAST:event_jTextFieldImporteFocusLost

    private void jTextFieldFechaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFechaFocusGained
        flagFechaMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextFieldFecha, flagFechaMovimiento);
    }//GEN-LAST:event_jTextFieldFechaFocusGained

    private void jTextFieldFechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFechaFocusLost
        if (jTextFieldFecha.getText().isEmpty()) {
            flagFechaMovimiento = controladorInsertadoDeDatos.RellenarCampos("20/01/2000", jTextFieldFecha, flagFechaMovimiento);

        } 
    }//GEN-LAST:event_jTextFieldFechaFocusLost

    private void jTextFieldImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldImporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldImporteActionPerformed

    private void jTextAreaDescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAreaDescripcionFocusGained
        flagDescripcionMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextAreaDescripcion, flagDescripcionMovimiento);
    }//GEN-LAST:event_jTextAreaDescripcionFocusGained

    private void jTextAreaDescripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAreaDescripcionFocusLost
        if (jTextFieldFecha.getText().isEmpty()) {
            flagDescripcionMovimiento = controladorInsertadoDeDatos.RellenarCampos("Descripción", jTextAreaDescripcion, flagDescripcionMovimiento);

        } 
    }//GEN-LAST:event_jTextAreaDescripcionFocusLost

    private void jButtonInsertarBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarBinarioActionPerformed
        flagDescripcionMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextAreaDescripcion, flagDescripcionMovimiento);
        flagFechaMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextFieldFecha, flagFechaMovimiento);
        flagImporteMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextFieldImporte, flagImporteMovimiento);
        flagIdMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextFieldNumeroDeMovimiento, flagIdMovimiento);
        flagApellidoEmpleado = controladorInsertadoDeDatos.VaciarCampos(jTextFieldApellido, flagApellidoEmpleado);
        flagNombreEmpleado = controladorInsertadoDeDatos.VaciarCampos(jTextFieldNombre, flagNombreEmpleado);
        flagNumeroEmpleado = controladorInsertadoDeDatos.VaciarCampos(jTextFieldNumerodeEmpleado, flagNumeroEmpleado);
        boolean control = controladorInsertadoDeDatos.InsertarDatosBinario();
        if (control == false) {
            if (jTextFieldFecha.getText().isEmpty()) {
                flagDescripcionMovimiento = controladorInsertadoDeDatos.RellenarCampos("Descripción", jTextAreaDescripcion, flagDescripcionMovimiento);

            }
            if (jTextFieldFecha.getText().isEmpty()) {
                flagFechaMovimiento = controladorInsertadoDeDatos.RellenarCampos("20/01/2000", jTextFieldFecha, flagFechaMovimiento);

            }
            if (jTextFieldImporte.getText().isEmpty()) {
                flagImporteMovimiento = controladorInsertadoDeDatos.RellenarCampos("Importe", jTextFieldImporte, flagImporteMovimiento);

            }
            if (jTextFieldNumeroDeMovimiento.getText().isEmpty()) {
                flagIdMovimiento = controladorInsertadoDeDatos.RellenarCampos("Numero de Movimiento", jTextFieldNumeroDeMovimiento, flagIdMovimiento);

            }
            if (jTextFieldApellido.getText().isEmpty()) {
                flagApellidoEmpleado = controladorInsertadoDeDatos.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);

            }
            if (jTextFieldNombre.getText().isEmpty()) {
                flagNombreEmpleado = controladorInsertadoDeDatos.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);

            }
            if (jTextFieldNumerodeEmpleado.getText().isEmpty()) {
                flagNumeroEmpleado = controladorInsertadoDeDatos.RellenarCampos("Numero", jTextFieldNumerodeEmpleado, flagNumeroEmpleado);

            }
        } else {
            flagDescripcionMovimiento = controladorInsertadoDeDatos.RellenarCampos("Descripción", jTextAreaDescripcion, flagDescripcionMovimiento);
            flagFechaMovimiento = controladorInsertadoDeDatos.RellenarCampos("20/01/2000", jTextFieldFecha, flagFechaMovimiento);
            flagImporteMovimiento = controladorInsertadoDeDatos.RellenarCampos("Importe", jTextFieldImporte, flagImporteMovimiento);
            flagIdMovimiento = controladorInsertadoDeDatos.RellenarCampos("Numero de Movimiento", jTextFieldNumeroDeMovimiento, flagIdMovimiento);
            flagApellidoEmpleado = controladorInsertadoDeDatos.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);
            flagNombreEmpleado = controladorInsertadoDeDatos.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);
            flagNumeroEmpleado = controladorInsertadoDeDatos.RellenarCampos("Numero", jTextFieldNumerodeEmpleado, flagNumeroEmpleado);
        }
    }//GEN-LAST:event_jButtonInsertarBinarioActionPerformed

    private void jTextFieldNumerodeEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumerodeEmpleadoKeyTyped
        controladorInsertadoDeDatos.limitadorNumeros(evt);
    }//GEN-LAST:event_jTextFieldNumerodeEmpleadoKeyTyped

    private void jTextFieldNumeroDeMovimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroDeMovimientoKeyTyped
        controladorInsertadoDeDatos.limitadorNumeros(evt);
    }//GEN-LAST:event_jTextFieldNumeroDeMovimientoKeyTyped

    private void jTextFieldImporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldImporteKeyTyped
      controladorInsertadoDeDatos.limitadorNumeros(evt);
    }//GEN-LAST:event_jTextFieldImporteKeyTyped

    private void jButtonInsertarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarTextoActionPerformed
       flagDescripcionMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextAreaDescripcion, flagDescripcionMovimiento);
        flagFechaMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextFieldFecha, flagFechaMovimiento);
        flagImporteMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextFieldImporte, flagImporteMovimiento);
        flagIdMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextFieldNumeroDeMovimiento, flagIdMovimiento);
        flagApellidoEmpleado = controladorInsertadoDeDatos.VaciarCampos(jTextFieldApellido, flagApellidoEmpleado);
        flagNombreEmpleado = controladorInsertadoDeDatos.VaciarCampos(jTextFieldNombre, flagNombreEmpleado);
        flagNumeroEmpleado = controladorInsertadoDeDatos.VaciarCampos(jTextFieldNumerodeEmpleado, flagNumeroEmpleado);
        boolean control = controladorInsertadoDeDatos.InsertarDatosTexto();
        if (control == false) {
            if (jTextFieldFecha.getText().isEmpty()) {
                flagDescripcionMovimiento = controladorInsertadoDeDatos.RellenarCampos("Descripción", jTextAreaDescripcion, flagDescripcionMovimiento);

            }
            if (jTextFieldFecha.getText().isEmpty()) {
                flagFechaMovimiento = controladorInsertadoDeDatos.RellenarCampos("20/01/2000", jTextFieldFecha, flagFechaMovimiento);

            }
            if (jTextFieldImporte.getText().isEmpty()) {
                flagImporteMovimiento = controladorInsertadoDeDatos.RellenarCampos("Importe", jTextFieldImporte, flagImporteMovimiento);

            }
            if (jTextFieldNumeroDeMovimiento.getText().isEmpty()) {
                flagIdMovimiento = controladorInsertadoDeDatos.RellenarCampos("Numero de Movimiento", jTextFieldNumeroDeMovimiento, flagIdMovimiento);

            }
            if (jTextFieldApellido.getText().isEmpty()) {
                flagApellidoEmpleado = controladorInsertadoDeDatos.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);

            }
            if (jTextFieldNombre.getText().isEmpty()) {
                flagNombreEmpleado = controladorInsertadoDeDatos.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);

            }
            if (jTextFieldNumerodeEmpleado.getText().isEmpty()) {
                flagNumeroEmpleado = controladorInsertadoDeDatos.RellenarCampos("Numero", jTextFieldNumerodeEmpleado, flagNumeroEmpleado);

            }
        } else {
            flagDescripcionMovimiento = controladorInsertadoDeDatos.RellenarCampos("Descripción", jTextAreaDescripcion, flagDescripcionMovimiento);
            flagFechaMovimiento = controladorInsertadoDeDatos.RellenarCampos("20/01/2000", jTextFieldFecha, flagFechaMovimiento);
            flagImporteMovimiento = controladorInsertadoDeDatos.RellenarCampos("Importe", jTextFieldImporte, flagImporteMovimiento);
            flagIdMovimiento = controladorInsertadoDeDatos.RellenarCampos("Numero de Movimiento", jTextFieldNumeroDeMovimiento, flagIdMovimiento);
            flagApellidoEmpleado = controladorInsertadoDeDatos.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);
            flagNombreEmpleado = controladorInsertadoDeDatos.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);
            flagNumeroEmpleado = controladorInsertadoDeDatos.RellenarCampos("Numero", jTextFieldNumerodeEmpleado, flagNumeroEmpleado);
        }
    }//GEN-LAST:event_jButtonInsertarTextoActionPerformed

    private void jButtonInsertarObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarObjetoActionPerformed
           flagDescripcionMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextAreaDescripcion, flagDescripcionMovimiento);
        flagFechaMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextFieldFecha, flagFechaMovimiento);
        flagImporteMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextFieldImporte, flagImporteMovimiento);
        flagIdMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextFieldNumeroDeMovimiento, flagIdMovimiento);
        flagApellidoEmpleado = controladorInsertadoDeDatos.VaciarCampos(jTextFieldApellido, flagApellidoEmpleado);
        flagNombreEmpleado = controladorInsertadoDeDatos.VaciarCampos(jTextFieldNombre, flagNombreEmpleado);
        flagNumeroEmpleado = controladorInsertadoDeDatos.VaciarCampos(jTextFieldNumerodeEmpleado, flagNumeroEmpleado);
        boolean control = controladorInsertadoDeDatos.InsertarDatosObjeto();
        if (control == false) {
            if (jTextFieldFecha.getText().isEmpty()) {
                flagDescripcionMovimiento = controladorInsertadoDeDatos.RellenarCampos("Descripción", jTextAreaDescripcion, flagDescripcionMovimiento);

            }
            if (jTextFieldFecha.getText().isEmpty()) {
                flagFechaMovimiento = controladorInsertadoDeDatos.RellenarCampos("20/01/2000", jTextFieldFecha, flagFechaMovimiento);

            }
            if (jTextFieldImporte.getText().isEmpty()) {
                flagImporteMovimiento = controladorInsertadoDeDatos.RellenarCampos("Importe", jTextFieldImporte, flagImporteMovimiento);

            }
            if (jTextFieldNumeroDeMovimiento.getText().isEmpty()) {
                flagIdMovimiento = controladorInsertadoDeDatos.RellenarCampos("Numero de Movimiento", jTextFieldNumeroDeMovimiento, flagIdMovimiento);

            }
            if (jTextFieldApellido.getText().isEmpty()) {
                flagApellidoEmpleado = controladorInsertadoDeDatos.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);

            }
            if (jTextFieldNombre.getText().isEmpty()) {
                flagNombreEmpleado = controladorInsertadoDeDatos.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);

            }
            if (jTextFieldNumerodeEmpleado.getText().isEmpty()) {
                flagNumeroEmpleado = controladorInsertadoDeDatos.RellenarCampos("Numero", jTextFieldNumerodeEmpleado, flagNumeroEmpleado);

            }
        } else {
            flagDescripcionMovimiento = controladorInsertadoDeDatos.RellenarCampos("Descripción", jTextAreaDescripcion, flagDescripcionMovimiento);
            flagFechaMovimiento = controladorInsertadoDeDatos.RellenarCampos("20/01/2000", jTextFieldFecha, flagFechaMovimiento);
            flagImporteMovimiento = controladorInsertadoDeDatos.RellenarCampos("Importe", jTextFieldImporte, flagImporteMovimiento);
            flagIdMovimiento = controladorInsertadoDeDatos.RellenarCampos("Numero de Movimiento", jTextFieldNumeroDeMovimiento, flagIdMovimiento);
            flagApellidoEmpleado = controladorInsertadoDeDatos.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);
            flagNombreEmpleado = controladorInsertadoDeDatos.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);
            flagNumeroEmpleado = controladorInsertadoDeDatos.RellenarCampos("Numero", jTextFieldNumerodeEmpleado, flagNumeroEmpleado);
        }
    }//GEN-LAST:event_jButtonInsertarObjetoActionPerformed

    private void jButtonInsertarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarXMLActionPerformed
       flagDescripcionMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextAreaDescripcion, flagDescripcionMovimiento);
        flagFechaMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextFieldFecha, flagFechaMovimiento);
        flagImporteMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextFieldImporte, flagImporteMovimiento);
        flagIdMovimiento = controladorInsertadoDeDatos.VaciarCampos(jTextFieldNumeroDeMovimiento, flagIdMovimiento);
        flagApellidoEmpleado = controladorInsertadoDeDatos.VaciarCampos(jTextFieldApellido, flagApellidoEmpleado);
        flagNombreEmpleado = controladorInsertadoDeDatos.VaciarCampos(jTextFieldNombre, flagNombreEmpleado);
        flagNumeroEmpleado = controladorInsertadoDeDatos.VaciarCampos(jTextFieldNumerodeEmpleado, flagNumeroEmpleado);
        boolean control =  controladorInsertadoDeDatos.InsertarDatosXml();;
        if (control == false) {
            if (jTextFieldFecha.getText().isEmpty()) {
                flagDescripcionMovimiento = controladorInsertadoDeDatos.RellenarCampos("Descripción", jTextAreaDescripcion, flagDescripcionMovimiento);

            }
            if (jTextFieldFecha.getText().isEmpty()) {
                flagFechaMovimiento = controladorInsertadoDeDatos.RellenarCampos("20/01/2000", jTextFieldFecha, flagFechaMovimiento);

            }
            if (jTextFieldImporte.getText().isEmpty()) {
                flagImporteMovimiento = controladorInsertadoDeDatos.RellenarCampos("Importe", jTextFieldImporte, flagImporteMovimiento);

            }
            if (jTextFieldNumeroDeMovimiento.getText().isEmpty()) {
                flagIdMovimiento = controladorInsertadoDeDatos.RellenarCampos("Numero de Movimiento", jTextFieldNumeroDeMovimiento, flagIdMovimiento);

            }
            if (jTextFieldApellido.getText().isEmpty()) {
                flagApellidoEmpleado = controladorInsertadoDeDatos.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);

            }
            if (jTextFieldNombre.getText().isEmpty()) {
                flagNombreEmpleado = controladorInsertadoDeDatos.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);

            }
            if (jTextFieldNumerodeEmpleado.getText().isEmpty()) {
                flagNumeroEmpleado = controladorInsertadoDeDatos.RellenarCampos("Numero", jTextFieldNumerodeEmpleado, flagNumeroEmpleado);

            }
        } else {
            flagDescripcionMovimiento = controladorInsertadoDeDatos.RellenarCampos("Descripción", jTextAreaDescripcion, flagDescripcionMovimiento);
            flagFechaMovimiento = controladorInsertadoDeDatos.RellenarCampos("20/01/2000", jTextFieldFecha, flagFechaMovimiento);
            flagImporteMovimiento = controladorInsertadoDeDatos.RellenarCampos("Importe", jTextFieldImporte, flagImporteMovimiento);
            flagIdMovimiento = controladorInsertadoDeDatos.RellenarCampos("Numero de Movimiento", jTextFieldNumeroDeMovimiento, flagIdMovimiento);
            flagApellidoEmpleado = controladorInsertadoDeDatos.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);
            flagNombreEmpleado = controladorInsertadoDeDatos.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);
            flagNumeroEmpleado = controladorInsertadoDeDatos.RellenarCampos("Numero", jTextFieldNumerodeEmpleado, flagNumeroEmpleado);
        }
        
       
    }//GEN-LAST:event_jButtonInsertarXMLActionPerformed

    public boolean isFlagNumeroEmpleado() {
        return flagNumeroEmpleado;
    }

    public void setFlagNumeroEmpleado(boolean flagNumeroEmpleado) {
        this.flagNumeroEmpleado = flagNumeroEmpleado;
    }

    public boolean isFlagNombreEmpleado() {
        return flagNombreEmpleado;
    }

    public void setFlagNombreEmpleado(boolean flagNombreEmpleado) {
        this.flagNombreEmpleado = flagNombreEmpleado;
    }

    public boolean isFlagApellidoEmpleado() {
        return flagApellidoEmpleado;
    }

    public void setFlagApellidoEmpleado(boolean flagApellidoEmpleado) {
        this.flagApellidoEmpleado = flagApellidoEmpleado;
    }

    public boolean isFlagIdMovimiento() {
        return flagIdMovimiento;
    }

    public void setFlagIdMovimiento(boolean flagIdMovimiento) {
        this.flagIdMovimiento = flagIdMovimiento;
    }

    public boolean isFlagImporteMovimiento() {
        return flagImporteMovimiento;
    }

    public void setFlagImporteMovimiento(boolean flagImporteMovimiento) {
        this.flagImporteMovimiento = flagImporteMovimiento;
    }

    public boolean isFlagFechaMovimiento() {
        return flagFechaMovimiento;
    }

    public void setFlagFechaMovimiento(boolean flagFechaMovimiento) {
        this.flagFechaMovimiento = flagFechaMovimiento;
    }

    public JButton getjButtonInsertar() {
        return jButtonInsertarObjeto;
    }

    public void setjButtonInsertar(JButton jButtonInsertar) {
        this.jButtonInsertarObjeto = jButtonInsertar;
    }

    public JComboBox getjComboBoxTipo() {
        return jComboBoxTipo;
    }

    public void setjComboBoxTipo(JComboBox jComboBoxTipo) {
        this.jComboBoxTipo = jComboBoxTipo;
    }

    public JTextField getjTextFieldApellido() {
        return jTextFieldApellido;
    }

    public void setjTextFieldApellido(JTextField jTextFieldApellido) {
        this.jTextFieldApellido = jTextFieldApellido;
    }

    public JTextField getjTextFieldFecha() {
        return jTextFieldFecha;
    }

    public void setjTextFieldFecha(JTextField jTextFieldFecha) {
        this.jTextFieldFecha = jTextFieldFecha;
    }

    public JTextField getjTextFieldNumeroDeMovimiento() {
        return jTextFieldNumeroDeMovimiento;
    }

    public void setjTextFieldNumeroDeMovimiento(JTextField jTextFieldId) {
        this.jTextFieldNumeroDeMovimiento = jTextFieldId;
    }

    public JTextField getjTextFieldImporte() {
        return jTextFieldImporte;
    }

    public void setjTextFieldImporte(JTextField jTextFieldImporte) {
        this.jTextFieldImporte = jTextFieldImporte;
    }

    public JTextField getjTextFieldNombre() {
        return jTextFieldNombre;
    }

    public void setjTextFieldNombre(JTextField jTextFieldNombre) {
        this.jTextFieldNombre = jTextFieldNombre;
    }

    public JTextField getjTextFieldNumerodeEmpleado() {
        return jTextFieldNumerodeEmpleado;
    }

    public void setjTextFieldNumerodeEmpleado(JTextField jTextFieldNumerodeEmpleado) {
        this.jTextFieldNumerodeEmpleado = jTextFieldNumerodeEmpleado;
    }

    public boolean isFlagDescripcionMovimiento() {
        return flagDescripcionMovimiento;
    }

    public JTextArea getjTextAreaDescripcion() {
        return jTextAreaDescripcion;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogInsertadoDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogInsertadoDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogInsertadoDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogInsertadoDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogInsertadoDeDatos dialog = new JDialogInsertadoDeDatos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInsertarBinario;
    private javax.swing.JButton jButtonInsertarObjeto;
    private javax.swing.JButton jButtonInsertarTexto;
    private javax.swing.JButton jButtonInsertarXML;
    private javax.swing.JComboBox jComboBoxTipo;
    private javax.swing.JLabel jLabelInsertarDatos;
    private javax.swing.JPanel jPanelInsertarDatos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldImporte;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumeroDeMovimiento;
    private javax.swing.JTextField jTextFieldNumerodeEmpleado;
    // End of variables declaration//GEN-END:variables
}
