/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionDeMovimientos.vista;

import gestionDeMovimientos.controlador.ControladorInsertardoDeEmpleados;
import javax.swing.JButton;
import javax.swing.JTextField;
/**
 *
 * @author jesus
 */
public class JDialogInsertadoEmpleados extends javax.swing.JDialog {

    private ControladorInsertardoDeEmpleados controladorInsertadoDeEmpleados;
    private boolean flagNumeroEmpleado = false;
    private boolean flagNombreEmpleado = false;
    private boolean flagApellidoEmpleado = false;


    public JDialogInsertadoEmpleados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controladorInsertadoDeEmpleados = new ControladorInsertardoDeEmpleados(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInsertarDatos = new javax.swing.JPanel();
        jLabelInsertarDatos = new javax.swing.JLabel();
        jTextFieldNumerodeEmpleado = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jButtonInsertarTexto = new javax.swing.JButton();
        jButtonInsertarBinario = new javax.swing.JButton();
        jButtonInsertarObjeto = new javax.swing.JButton();
        jButtonInsertarXML = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelInsertarDatos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelInsertarDatos.setText("Insertar Empleados");

        jTextFieldNumerodeEmpleado.setForeground(new java.awt.Color(126, 126, 126));
        jTextFieldNumerodeEmpleado.setText("Numero");
        jTextFieldNumerodeEmpleado.setToolTipText("Numero de Empleado");
        jTextFieldNumerodeEmpleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNumerodeEmpleadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumerodeEmpleadoFocusLost(evt);
            }
        });
        jTextFieldNumerodeEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumerodeEmpleadoKeyTyped(evt);
            }
        });

        jTextFieldNombre.setForeground(new java.awt.Color(126, 126, 126));
        jTextFieldNombre.setText("Nombre");
        jTextFieldNombre.setToolTipText("Nombre del Empleado");
        jTextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusLost(evt);
            }
        });

        jTextFieldApellido.setForeground(new java.awt.Color(126, 126, 126));
        jTextFieldApellido.setText("Apellidos");
        jTextFieldApellido.setToolTipText("Apellidos del Empleado");
        jTextFieldApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldApellidoFocusLost(evt);
            }
        });

        jButtonInsertarTexto.setText("Texto");
        jButtonInsertarTexto.setToolTipText("Insertar los datos en el archivo Texto");
        jButtonInsertarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarTextoActionPerformed(evt);
            }
        });

        jButtonInsertarBinario.setText("Binario");
        jButtonInsertarBinario.setToolTipText("Insertar los datos en el archivo Binario");
        jButtonInsertarBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarBinarioActionPerformed(evt);
            }
        });

        jButtonInsertarObjeto.setText("Objeto");
        jButtonInsertarObjeto.setToolTipText("Insertar los datos en el archivo Objeto");
        jButtonInsertarObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarObjetoActionPerformed(evt);
            }
        });

        jButtonInsertarXML.setText("XML");
        jButtonInsertarXML.setToolTipText("Insertar los datos en el archivo XML");
        jButtonInsertarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarXMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInsertarDatosLayout = new javax.swing.GroupLayout(jPanelInsertarDatos);
        jPanelInsertarDatos.setLayout(jPanelInsertarDatosLayout);
        jPanelInsertarDatosLayout.setHorizontalGroup(
            jPanelInsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertarDatosLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanelInsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertarDatosLayout.createSequentialGroup()
                        .addComponent(jTextFieldNumerodeEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertarDatosLayout.createSequentialGroup()
                        .addComponent(jButtonInsertarTexto)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInsertarBinario)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonInsertarObjeto)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonInsertarXML)))
                .addGap(65, 65, 65))
            .addGroup(jPanelInsertarDatosLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabelInsertarDatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInsertarDatosLayout.setVerticalGroup(
            jPanelInsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertarDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelInsertarDatos)
                .addGap(33, 33, 33)
                .addGroup(jPanelInsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumerodeEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelInsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertarTexto)
                    .addComponent(jButtonInsertarBinario)
                    .addComponent(jButtonInsertarObjeto)
                    .addComponent(jButtonInsertarXML))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInsertarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelInsertarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNumerodeEmpleadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumerodeEmpleadoFocusGained
        flagNumeroEmpleado = controladorInsertadoDeEmpleados.VaciarCampos(jTextFieldNumerodeEmpleado, flagNumeroEmpleado);
    }//GEN-LAST:event_jTextFieldNumerodeEmpleadoFocusGained

    private void jTextFieldNumerodeEmpleadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumerodeEmpleadoFocusLost
        if (jTextFieldNumerodeEmpleado.getText().isEmpty()) {
            flagNumeroEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Numero", jTextFieldNumerodeEmpleado, flagNumeroEmpleado);

        }
    }//GEN-LAST:event_jTextFieldNumerodeEmpleadoFocusLost

    private void jTextFieldNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusGained
        flagNombreEmpleado = controladorInsertadoDeEmpleados.VaciarCampos(jTextFieldNombre, flagNombreEmpleado);
    }//GEN-LAST:event_jTextFieldNombreFocusGained

    private void jTextFieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusLost
        if (jTextFieldNombre.getText().isEmpty()) {
            flagNombreEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);

        }
    }//GEN-LAST:event_jTextFieldNombreFocusLost

    private void jTextFieldApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldApellidoFocusGained
        flagApellidoEmpleado = controladorInsertadoDeEmpleados.VaciarCampos(jTextFieldApellido, flagApellidoEmpleado);
    }//GEN-LAST:event_jTextFieldApellidoFocusGained

    private void jTextFieldApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldApellidoFocusLost
        if (jTextFieldApellido.getText().isEmpty()) {
            flagApellidoEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);

        }
    }//GEN-LAST:event_jTextFieldApellidoFocusLost

    private void jButtonInsertarBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarBinarioActionPerformed

        flagApellidoEmpleado = controladorInsertadoDeEmpleados.VaciarCampos(jTextFieldApellido, flagApellidoEmpleado);
        flagNombreEmpleado = controladorInsertadoDeEmpleados.VaciarCampos(jTextFieldNombre, flagNombreEmpleado);
        flagNumeroEmpleado = controladorInsertadoDeEmpleados.VaciarCampos(jTextFieldNumerodeEmpleado, flagNumeroEmpleado);
        boolean control = controladorInsertadoDeEmpleados.InsertarDatosBinario();
        if (control == false) {

            if (jTextFieldApellido.getText().isEmpty()) {
                flagApellidoEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);

            }
            if (jTextFieldNombre.getText().isEmpty()) {
                flagNombreEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);

            }
            if (jTextFieldNumerodeEmpleado.getText().isEmpty()) {
                flagNumeroEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Numero", jTextFieldNumerodeEmpleado, flagNumeroEmpleado);

            }
        } else {

            flagApellidoEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);
            flagNombreEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);
            flagNumeroEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Numero", jTextFieldNumerodeEmpleado, flagNumeroEmpleado);
        }
    }//GEN-LAST:event_jButtonInsertarBinarioActionPerformed

    private void jTextFieldNumerodeEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumerodeEmpleadoKeyTyped
        controladorInsertadoDeEmpleados.limitadorNumeros(evt);
    }//GEN-LAST:event_jTextFieldNumerodeEmpleadoKeyTyped

    private void jButtonInsertarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarTextoActionPerformed
        flagApellidoEmpleado = controladorInsertadoDeEmpleados.VaciarCampos(jTextFieldApellido, flagApellidoEmpleado);
        flagNombreEmpleado = controladorInsertadoDeEmpleados.VaciarCampos(jTextFieldNombre, flagNombreEmpleado);
        flagNumeroEmpleado = controladorInsertadoDeEmpleados.VaciarCampos(jTextFieldNumerodeEmpleado, flagNumeroEmpleado);
        boolean control = controladorInsertadoDeEmpleados.InsertarEmpleadosTexto();
        if (control == false) {

            if (jTextFieldApellido.getText().isEmpty()) {
                flagApellidoEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);

            }
            if (jTextFieldNombre.getText().isEmpty()) {
                flagNombreEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);

            }
            if (jTextFieldNumerodeEmpleado.getText().isEmpty()) {
                flagNumeroEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Numero", jTextFieldNumerodeEmpleado, flagNumeroEmpleado);

            }
        } else {
            flagApellidoEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);
            flagNombreEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);
            flagNumeroEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Numero", jTextFieldNumerodeEmpleado, flagNumeroEmpleado);
        }
    }//GEN-LAST:event_jButtonInsertarTextoActionPerformed

    private void jButtonInsertarObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarObjetoActionPerformed
     flagApellidoEmpleado = controladorInsertadoDeEmpleados.VaciarCampos(jTextFieldApellido, flagApellidoEmpleado);
        flagNombreEmpleado = controladorInsertadoDeEmpleados.VaciarCampos(jTextFieldNombre, flagNombreEmpleado);
        flagNumeroEmpleado = controladorInsertadoDeEmpleados.VaciarCampos(jTextFieldNumerodeEmpleado, flagNumeroEmpleado);
        boolean control = controladorInsertadoDeEmpleados.InsertarEmpleadosObjetos();
        if (control == false) {

            if (jTextFieldApellido.getText().isEmpty()) {
                flagApellidoEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);

            }
            if (jTextFieldNombre.getText().isEmpty()) {
                flagNombreEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);

            }
            if (jTextFieldNumerodeEmpleado.getText().isEmpty()) {
                flagNumeroEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Numero", jTextFieldNumerodeEmpleado, flagNumeroEmpleado);

            }
        } else {
            flagApellidoEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);
            flagNombreEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);
            flagNumeroEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Numero", jTextFieldNumerodeEmpleado, flagNumeroEmpleado);
        }
    }//GEN-LAST:event_jButtonInsertarObjetoActionPerformed

    private void jButtonInsertarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarXMLActionPerformed
  flagApellidoEmpleado = controladorInsertadoDeEmpleados.VaciarCampos(jTextFieldApellido, flagApellidoEmpleado);
        flagNombreEmpleado = controladorInsertadoDeEmpleados.VaciarCampos(jTextFieldNombre, flagNombreEmpleado);
        flagNumeroEmpleado = controladorInsertadoDeEmpleados.VaciarCampos(jTextFieldNumerodeEmpleado, flagNumeroEmpleado);
        boolean control = controladorInsertadoDeEmpleados.InsertarEmpleadosXML();
        if (control == false) {

            if (jTextFieldApellido.getText().isEmpty()) {
                flagApellidoEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);

            }
            if (jTextFieldNombre.getText().isEmpty()) {
                flagNombreEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);

            }
            if (jTextFieldNumerodeEmpleado.getText().isEmpty()) {
                flagNumeroEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Numero", jTextFieldNumerodeEmpleado, flagNumeroEmpleado);

            }
        } else {
            flagApellidoEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);
            flagNombreEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);
            flagNumeroEmpleado = controladorInsertadoDeEmpleados.RellenarCampos("Numero", jTextFieldNumerodeEmpleado, flagNumeroEmpleado);
        }
    }//GEN-LAST:event_jButtonInsertarXMLActionPerformed

    public boolean isFlagNumeroEmpleado() {
        return flagNumeroEmpleado;
    }

    public void setFlagNumeroEmpleado(boolean flagNumeroEmpleado) {
        this.flagNumeroEmpleado = flagNumeroEmpleado;
    }

    public boolean isFlagNombreEmpleado() {
        return flagNombreEmpleado;
    }

    public void setFlagNombreEmpleado(boolean flagNombreEmpleado) {
        this.flagNombreEmpleado = flagNombreEmpleado;
    }

    public boolean isFlagApellidoEmpleado() {
        return flagApellidoEmpleado;
    }

    public void setFlagApellidoEmpleado(boolean flagApellidoEmpleado) {
        this.flagApellidoEmpleado = flagApellidoEmpleado;
    }

    public JButton getjButtonInsertar() {
        return jButtonInsertarObjeto;
    }

    public void setjButtonInsertar(JButton jButtonInsertar) {
        this.jButtonInsertarObjeto = jButtonInsertar;
    }

    public JTextField getjTextFieldApellido() {
        return jTextFieldApellido;
    }

    public void setjTextFieldApellido(JTextField jTextFieldApellido) {
        this.jTextFieldApellido = jTextFieldApellido;
    }

    public JTextField getjTextFieldNombre() {
        return jTextFieldNombre;
    }

    public void setjTextFieldNombre(JTextField jTextFieldNombre) {
        this.jTextFieldNombre = jTextFieldNombre;
    }

    public JTextField getjTextFieldNumerodeEmpleado() {
        return jTextFieldNumerodeEmpleado;
    }

    public void setjTextFieldNumerodeEmpleado(JTextField jTextFieldNumerodeEmpleado) {
        this.jTextFieldNumerodeEmpleado = jTextFieldNumerodeEmpleado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogInsertadoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogInsertadoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogInsertadoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogInsertadoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogInsertadoEmpleados dialog = new JDialogInsertadoEmpleados(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInsertarBinario;
    private javax.swing.JButton jButtonInsertarObjeto;
    private javax.swing.JButton jButtonInsertarTexto;
    private javax.swing.JButton jButtonInsertarXML;
    private javax.swing.JLabel jLabelInsertarDatos;
    private javax.swing.JPanel jPanelInsertarDatos;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumerodeEmpleado;
    // End of variables declaration//GEN-END:variables
}
