/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionDeMovimientos.vista;
import gestionDeMovimientos.controlador.ControladorVisionadoDeEmpleados;
/**
 *
 * @author jesus
 */
public class JFrameVisionadoDeEmpleados extends javax.swing.JFrame {
      private final ControladorVisionadoDeEmpleados controladorVisionadoDeDatos;
    /**
     * Creates new form visionadoDeDatos
     */
    public JFrameVisionadoDeEmpleados() {
        initComponents();
        controladorVisionadoDeDatos = new ControladorVisionadoDeEmpleados(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jButtonVerTexto = new javax.swing.JButton();
        jButtonVerBinario = new javax.swing.JButton();
        jButtonVerObjeto = new javax.swing.JButton();
        jButtonVerXML = new javax.swing.JButton();
        jMenuBarVisionadoDeDatos = new javax.swing.JMenuBar();
        jMenuInsertadoDeDatos = new javax.swing.JMenu();
        jMenuItemInsertadoDeDatosGeneral = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero De Empleado", "Nombre", "Apellido", "Cantidad De Movimientos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableEmpleados);

        jButtonVerTexto.setText("Texto");
        jButtonVerTexto.setToolTipText("Insertar los datos en el archivo Texto");
        jButtonVerTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerTextoActionPerformed(evt);
            }
        });

        jButtonVerBinario.setText("Binario");
        jButtonVerBinario.setToolTipText("Insertar los datos en el archivo Binario");
        jButtonVerBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerBinarioActionPerformed(evt);
            }
        });

        jButtonVerObjeto.setText("Objeto");
        jButtonVerObjeto.setToolTipText("Insertar los datos en el archivo Objeto");

        jButtonVerXML.setText("XML");
        jButtonVerXML.setToolTipText("Insertar los datos en el archivo XML");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButtonVerTexto)
                .addGap(18, 18, 18)
                .addComponent(jButtonVerBinario)
                .addGap(26, 26, 26)
                .addComponent(jButtonVerObjeto)
                .addGap(31, 31, 31)
                .addComponent(jButtonVerXML)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVerBinario)
                    .addComponent(jButtonVerObjeto)
                    .addComponent(jButtonVerXML)
                    .addComponent(jButtonVerTexto))
                .addGap(0, 48, Short.MAX_VALUE))
        );

        jMenuInsertadoDeDatos.setText("Insertar Datos");

        jMenuItemInsertadoDeDatosGeneral.setText("Insertar Movimientos");
        jMenuItemInsertadoDeDatosGeneral.setToolTipText("Inserta todos los datos de movimientos y usuario");
        jMenuItemInsertadoDeDatosGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInsertadoDeDatosGeneralActionPerformed(evt);
            }
        });
        jMenuInsertadoDeDatos.add(jMenuItemInsertadoDeDatosGeneral);

        jMenuBarVisionadoDeDatos.add(jMenuInsertadoDeDatos);

        setJMenuBar(jMenuBarVisionadoDeDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemInsertadoDeDatosGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInsertadoDeDatosGeneralActionPerformed
        controladorVisionadoDeDatos.AbrirInsertadoDeDatos();
    }//GEN-LAST:event_jMenuItemInsertadoDeDatosGeneralActionPerformed

    private void jButtonVerBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerBinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVerBinarioActionPerformed

    private void jButtonVerTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerTextoActionPerformed
     controladorVisionadoDeDatos.RellenarTabla(jTableEmpleados, 0);    // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVerTextoActionPerformed

    private void jTableEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmpleadosMouseClicked
   // controladorVisionadoDeDatos.        // TODO add your handling code here:
    }//GEN-LAST:event_jTableEmpleadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameVisionadoDeEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameVisionadoDeEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameVisionadoDeEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameVisionadoDeEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                    JFrameVisionadoDeEmpleados visionadoDeDatosCreado= new JFrameVisionadoDeEmpleados();
                    visionadoDeDatosCreado.setLocationRelativeTo(null);
                    visionadoDeDatosCreado.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVerBinario;
    private javax.swing.JButton jButtonVerObjeto;
    private javax.swing.JButton jButtonVerTexto;
    private javax.swing.JButton jButtonVerXML;
    private javax.swing.JMenuBar jMenuBarVisionadoDeDatos;
    private javax.swing.JMenu jMenuInsertadoDeDatos;
    private javax.swing.JMenuItem jMenuItemInsertadoDeDatosGeneral;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableEmpleados;
    // End of variables declaration//GEN-END:variables
}
